export { default as Startup } from './Startup/Startup';
export { default as Example } from './Example/Example';
export { default as Login } from './Login/Login';
export { default as HomeScreen } from './Home/Home';
export { default as MarriageScreen } from './Marriage/Marriage';
export { default as RegisterScreen } from './Register/Register';
export { default as ProfileScreen } from './Profile/Profile';
export { default as DonationScreen } from './Donation/Donation';
export { default as CoupleDetailScreen } from './Marriage/Couple';
